name: portal_cnab
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6+4
  get_storage: ^2.0.3
  http: ^0.13.5
  awesome_dialog: ^3.0.2
  file_picker: ^5.2.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7+3
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
